name: screen_translate
description: Screen Translate - A real-time screen translation app
publish_to: 'none'
version: 1.0.1+6

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.1.1
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  provider: ^6.1.2
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_commons: ^0.9.0
  flutter_screen_capture: ^1.0.0
  google_mlkit_translation: ^0.12.0
  translator: ^1.0.3+1
  crypto: ^3.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image: ^4.1.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  in_app_review: ^2.0.2
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_remote_config: ^6.1.3
  logging: ^1.2.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

intl:
  enabled: true